#ifndef BOOLEAN_H_INCLUDED
#define BOOLEAN_H_INCLUDED
#include <stdio.h>

typedef enum {FALSE, TRUE} boolean;

/// AGREGAR ACA LOS CABEZALES DE LOS PROCEDIMIENTOS CARGAR Y MOSTRAR DE PROGRAMACION 2

#endif // BOOLEAN_H_INCLUDED
